# Exported from Render on 2025-04-23T08:12:34Z
services:
- type: web
  name: airesumate-web.github.io
  runtime: node
  repo: https://github.com/airesumate-web/airesumate-web.github.io
  plan: free
  envVars:
  - key: OPENAI_API_KEY
    sync: false
  region: oregon
  buildCommand: yarn
  startCommand: yarn start
version: "1"
